import xml.etree.ElementTree as ET
import sys
import os
from re import T
import translators as ts
import xml.dom.minidom

locales = {
    "af": "af;af-NA;af-ZA",
"agq": "agq;agq-CM",
"ak": "ak;ak-GH",
"sq": "sq;sq-AL;sq-MK;sq-XK",
"am": "am;am-ET",
"ar": "ar;ar-001;ar-AE;ar-BH;ar-DJ;ar-DZ;ar-EG;ar-EH;ar-ER;ar-IL;ar-IQ;ar-JO;ar-KM;ar-KW;ar-LB;ar-LY;ar-MA;ar-MR;ar-OM;ar-PS;ar-QA;ar-SA;ar-SD;ar-SO;ar-SS;ar-SY;ar-TD;ar-TN;ar-YE",
"hy": "hy;hy-AM",
"as": "as;as-IN",
"ast": "ast;ast-ES",
"asa": "asa;asa-TZ",
"az": "az;az-Cyrl;az-Cyrl-AZ;az-Latn;az-Latn-AZ",
"ksf": "ksf;ksf-CM",
"bm": "bm;bm-ML",
"bn": "bn;bn-BD;bn-IN",
"bas": "bas;bas-CM",
"eu": "eu;eu-ES",
"be": "be;be-BY",
"bem": "bem;bem-ZM",
"bez": "bez;bez-TZ",
"bho": "bho;bho-IN",
"brx": "brx;brx-IN",
"bs": "bs;bs-Cyrl;bs-Cyrl-BA;bs-Latn;bs-Latn-BA",
"br": "br;br-FR",
"bg": "bg;bg-BG",
"my": "my;my-MM",
"yue": "yue;yue-Hans;yue-Hans-CN;yue-Hant;yue-Hant-HK",
"ca": "ca;ca-AD;ca-ES;ca-FR;ca-IT",
"ceb": "ceb;ceb-PH",
"tzm": "tzm;tzm-MA",
"ckb": "ckb;ckb-IQ;ckb-IR",
"ccp": "ccp;ccp-BD;ccp-IN",
"ce": "ce;ce-RU",
"chr": "chr;chr-US",
"cgg": "cgg;cgg-UG",
"zh": "zh;zh-Hans;zh-Hans-CN;zh-Hans-HK;zh-Hans-MO;zh-Hans-SG;zh-Hant;zh-Hant-HK;zh-Hant-MO;zh-Hant-TW",
"cv": "cv;cv-RU",
"ksh": "ksh;ksh-DE",
"kw": "kw;kw-GB",
"hr": "hr;hr-BA;hr-HR",
"cs": "cs;cs-CZ",
"da": "da;da-DK;da-GL",
"doi": "doi;doi-IN",
"dua": "dua;dua-CM",
"nl": "nl;nl-AW;nl-BE;nl-BQ;nl-CW;nl-NL;nl-SR;nl-SX",
"dz": "dz;dz-BT",
"ebu": "ebu;ebu-KE",
"eo": "eo;eo-001",
"et": "et;et-EE",
"ee": "ee;ee-GH;ee-TG",
"ewo": "ewo;ewo-CM",
"fo": "fo;fo-DK;fo-FO",
"fil": "fil;fil-PH",
"fi": "fi;fi-FI",
"fr": "fr;fr-BE;fr-BF;fr-BI;fr-BJ;fr-BL;fr-CA;fr-CD;fr-CF;fr-CG;fr-CH;fr-CI;fr-CM;fr-DJ;fr-DZ;fr-FR;fr-GA;fr-GF;fr-GN;fr-GP;fr-GQ;fr-HT;fr-KM;fr-LU;fr-MA;fr-MC;fr-MF;fr-MG;fr-ML;fr-MQ;fr-MR;fr-MU;fr-NC;fr-NE;fr-PF;fr-PM;fr-RE;fr-RW;fr-SC;fr-SN;fr-SY;fr-TD;fr-TG;fr-TN;fr-VU;fr-WF;fr-YT",
"fur": "fur;fur-IT",
"ff": "ff;ff-Adlm;ff-Adlm-BF;ff-Adlm-CM;ff-Adlm-GH;ff-Adlm-GM;ff-Adlm-GN;ff-Adlm-GW;ff-Adlm-LR;ff-Adlm-MR;ff-Adlm-NE;ff-Adlm-NG;ff-Adlm-SL;ff-Adlm-SN;ff-Latn;ff-Latn-BF;ff-Latn-CM;ff-Latn-GH;ff-Latn-GM;ff-Latn-GN;ff-Latn-GW;ff-Latn-LR;ff-Latn-MR;ff-Latn-NE;ff-Latn-NG;ff-Latn-SL;ff-Latn-SN",
"gl": "gl;gl-ES",
"lg": "lg;lg-UG",
"ka": "ka;ka-GE",
"de": "de;de-AT;de-BE;de-CH;de-DE;de-IT;de-LI;de-LU",
"el": "el;el-CY;el-GR",
"gu": "gu;gu-IN",
"guz": "guz;guz-KE",
"bgc": "bgc;bgc-IN",
"ha": "ha;ha-GH;ha-NE;ha-NG",
"haw": "haw;haw-US",
"he": "he;he-IL",
"hi": "hi;hi-IN;hi-Latn;hi-Latn-IN",
"hu": "hu;hu-HU",
"ja": "ja;ja-JP",
"jv": "jv;jv-ID",
"dyo": "dyo;dyo-SN",
"kea": "kea;kea-CV",
"kab": "kab;kab-DZ",
"kgp": "kgp;kgp-BR",
"kkj": "kkj;kkj-CM",
"kl": "kl;kl-GL",
"kln": "kln;kln-KE",
"kam": "kam;kam-KE",
"kn": "kn;kn-IN",
"ks": "ks;ks-Arab;ks-Arab-IN;ks-Deva;ks-Deva-IN",
"kk": "kk;kk-KZ",
"km": "km;km-KH",
"ki": "ki;ki-KE",
"rw": "rw;rw-RW",
"kok": "kok;kok-IN",
"ko": "ko;ko-KP;ko-KR",
"ses": "ses;ses-ML",
"khq": "khq;khq-ML",
"ku": "ku;ku-TR",
"nmg": "nmg;nmg-CM",
"ky": "ky;ky-KG",
"lkt": "lkt;lkt-US",
"lag": "lag;lag-TZ",
"lo": "lo;lo-LA",
"lv": "lv;lv-LV",
"ln": "ln;ln-AO;ln-CD;ln-CF;ln-CG",
"lt": "lt;lt-LT",
"dsb": "dsb;dsb-DE",
"lu": "lu;lu-CD",
"luo": "luo;luo-KE",
"lb": "lb;lb-LU",
"luy": "luy;luy-KE",
"mk": "mk;mk-MK",
"jmc": "jmc;jmc-TZ",
"mai": "mai;mai-IN",
"mgh": "mgh;mgh-MZ",
"kde": "kde;kde-TZ",
"mg": "mg;mg-MG",
"ms": "ms;ms-BN;ms-ID;ms-MY;ms-SG",
"ml": "ml;ml-IN",
"mt": "mt;mt-MT",
"mni": "mni;mni-Beng;mni-Beng-IN",
"gv": "gv;gv-IM",
"mr": "mr;mr-IN",
"mas": "mas;mas-KE;mas-TZ",
"mzn": "mzn;mzn-IR",
"mer": "mer;mer-KE",
"mgo": "mgo;mgo-CM",
"mn": "mn;mn-MN",
"mfe": "mfe;mfe-MU",
"mua": "mua;mua-CM",
"mi": "mi;mi-NZ",
"naq": "naq;naq-NA",
"ne": "ne;ne-IN;ne-NP",
"nnh": "nnh;nnh-CM",
"jgo": "jgo;jgo-CM",
"yrl": "yrl;yrl-BR;yrl-CO;yrl-VE",
"pcm": "pcm;pcm-NG",
"lrc": "lrc;lrc-IQ;lrc-IR",
"se": "se;se-FI;se-NO;se-SE",
"nd": "nd;nd-ZW",
"no": "no",
"nb": "nb;nb-NO;nb-SJ",
"nn": "nn;nn-NO",
"nus": "nus;nus-SS",
"nyn": "nyn;nyn-UG",
"or": "or;or-IN",
"om": "om;om-ET;om-KE",
"os": "os;os-GE;os-RU",
"ps": "ps;ps-AF;ps-PK",
"fa": "fa;fa-AF;fa-IR",
"pl": "pl;pl-PL",
"pt": "pt;pt-AO;pt-BR;pt-CH;pt-CV;pt-GQ;pt-GW;pt-LU;pt-MO;pt-MZ;pt-PT;pt-ST;pt-TL",
"pa": "pa;pa-Arab;pa-Arab-PK;pa-Guru;pa-Guru-IN",
"qu": "qu;qu-BO;qu-EC;qu-PE",
"raj": "raj;raj-IN",
"ro": "ro;ro-MD;ro-RO",
"rm": "rm;rm-CH",
"rof": "rof;rof-TZ",
"rn": "rn;rn-BI",
"ru": "ru;ru-BY;ru-KG;ru-KZ;ru-MD;ru-RU;ru-UA",
"rwk": "rwk;rwk-TZ",
"saq": "saq;saq-KE",
"sg": "sg;sg-CF",
"sbp": "sbp;sbp-TZ",
"sa": "sa;sa-IN",
"sat": "sat;sat-Olck;sat-Olck-IN",
"sc": "sc;sc-IT",
"gd": "gd;gd-GB",
"seh": "seh;seh-MZ",
"sr": "sr;sr-Cyrl;sr-Cyrl-BA;sr-Cyrl-ME;sr-Cyrl-RS;sr-Cyrl-XK;sr-Latn;sr-Latn-BA;sr-Latn-ME;sr-Latn-RS;sr-Latn-XK",
"ksb": "ksb;ksb-TZ",
"sn": "sn;sn-ZW",
"ii": "ii;ii-CN",
"sd": "sd;sd-Arab;sd-Arab-PK;sd-Deva;sd-Deva-IN",
"si": "si;si-LK",
"sk": "sk;sk-SK",
"sl": "sl;sl-SI",
"xog": "xog;xog-UG",
"so": "so;so-DJ;so-ET;so-KE;so-SO",
"es": "es;es-419;es-AR;es-BO;es-BR;es-BZ;es-CL;es-CO;es-CR;es-CU;es-DO;es-EA;es-EC;es-ES;es-GQ;es-GT;es-HN;es-IC;es-MX;es-NI;es-PA;es-PE;es-PH;es-PR;es-PY;es-SV;es-US;es-UY;es-VE",
"zgh": "zgh;zgh-MA",
"su": "su;su-Latn;su-Latn-ID",
"sw": "sw;sw-CD;sw-KE;sw-TZ;sw-UG",
"sv": "sv;sv-AX;sv-FI;sv-SE",
"gsw": "gsw;gsw-CH;gsw-FR;gsw-LI",
"shi": "shi;shi-Latn;shi-Latn-MA;shi-Tfng;shi-Tfng-MA",
"dav": "dav;dav-KE",
"tg": "tg;tg-TJ",
"ta": "ta;ta-IN;ta-LK;ta-MY;ta-SG",
"twq": "twq;twq-NE",
"tt": "tt;tt-RU",
"te": "te;te-IN",
"teo": "teo;teo-KE;teo-UG",
"th": "th;th-TH",
"bo": "bo;bo-CN;bo-IN",
"ti": "ti;ti-ER;ti-ET",
"to": "to;to-TO",
"tk": "tk;tk-TM",
"uk": "uk;uk-UA",
"hsb": "hsb;hsb-DE",
"ur": "ur;ur-IN;ur-PK",
"ug": "ug;ug-CN",
"uz": "uz;uz-Arab;uz-Arab-AF;uz-Cyrl;uz-Cyrl-UZ;uz-Latn;uz-Latn-UZ",
"vai": "vai;vai-Latn;vai-Latn-LR;vai-Vaii;vai-Vaii-LR",
"vi": "vi;vi-VN",
"vun": "vun;vun-TZ",
"wae": "wae;wae-CH",
"cy": "cy;cy-GB",
"fy": "fy;fy-NL",
"wo": "wo;wo-SN",
"xh": "xh;xh-ZA",
"sah": "sah;sah-RU",
"yav": "yav;yav-CM",
"yi": "yi;yi-001",
"yo": "yo;yo-BJ;yo-NG",
"dje": "dje;dje-NE",
"zu": "zu;zu-ZA",
"is": "is;is-IS",
"ig": "ig;ig-NG",
"smn": "smn;smn-FI",
"id": "id;id-ID",
"ia": "ia;ia-001",
"ga": "ga;ga-GB;ga-IE",
"it": "it;it-CH;it-IT;it-SM;it-VA"
    }

languages = {
    "af": "Afrikaans",
"agq": "Aghem",
"ak": "Akan",
"sq": "shqip",
"am": "አማርኛ",
"ar": "العربية",
"hy": "հայերեն",
"as": "অসমীয়া",
"ast": "asturianu",
"asa": "Kipare",
"az": "azərbaycan",
"ksf": "rikpa",
"bm": "bamanakan",
"bn": "বাংলা",
"bas": "Ɓàsàa",
"eu": "euskara",
"be": "беларуская",
"bem": "Ichibemba",
"bez": "Hibena",
"bho": "भोजपुरी",
"brx": "बर’",
"bs": "bosanski",
"br": "brezhoneg",
"bg": "български",
"my": "မြန်မာ",
"yue": "粵語",
"ca": "català",
"ceb": "Cebuano",
"tzm": "Tamaziɣt n laṭlaṣ",
"ckb": "کوردیی ناوەندی",
"ccp": "𑄌𑄋𑄴𑄟𑄳𑄦",
"ce": "нохчийн",
"chr": "ᏣᎳᎩ",
"cgg": "Rukiga",
"zh": "中文",
"cv": "чӑваш",
"ksh": "Kölsch",
"kw": "kernewek",
"hr": "hrvatski",
"cs": "čeština",
"da": "dansk",
"doi": "डोगरी",
"dua": "duálá",
"nl": "Nederlands",
"dz": "རྫོང་ཁ",
"ebu": "Kĩembu",
"eo": "esperanto",
"et": "eesti",
"ee": "Eʋegbe",
"ewo": "ewondo",
"fo": "føroyskt",
"fil": "Filipino",
"fi": "suomi",
"fr": "français",
"fur": "furlan",
"ff": "Pulaar",
"gl": "galego",
"lg": "Luganda",
"ka": "ქართული",
"de": "Deutsch",
"el": "Ελληνικά",
"gu": "ગુજરાતી",
"guz": "Ekegusii",
"bgc": "हरियाणवी",
"ha": "Hausa",
"haw": "ʻŌlelo Hawaiʻi",
"he": "עברית",
"hi": "हिन्दी",
"hu": "magyar",
"ja": "日本語",
"jv": "Jawa",
"dyo": "joola",
"kea": "kabuverdianu",
"kab": "Taqbaylit",
"kgp": "kanhgág",
"kkj": "kakɔ",
"kl": "kalaallisut",
"kln": "Kalenjin",
"kam": "Kikamba",
"kn": "ಕನ್ನಡ",
"ks": "کٲشُر",
"kk": "қазақ тілі",
"km": "ខ្មែរ",
"ki": "Gikuyu",
"rw": "Kinyarwanda",
"kok": "कोंकणी",
"ko": "한국어",
"ses": "Koyraboro senni",
"khq": "Koyra ciini",
"ku": "kurdî",
"nmg": "Kwasio",
"ky": "кыргызча",
"lkt": "Lakȟólʼiyapi",
"lag": "Kɨlaangi",
"lo": "ລາວ",
"lv": "latviešu",
"ln": "lingála",
"lt": "lietuvių",
"dsb": "dolnoserbšćina",
"lu": "Tshiluba",
"luo": "Dholuo",
"lb": "Lëtzebuergesch",
"luy": "Luluhia",
"mk": "македонски",
"jmc": "Kimachame",
"mai": "मैथिली",
"mgh": "Makua",
"kde": "Chimakonde",
"mg": "Malagasy",
"ms": "Melayu",
"ml": "മലയാളം",
"mt": "Malti",
"mni": "মৈতৈলোন্",
"gv": "Gaelg",
"mr": "मराठी",
"mas": "Maa",
"mzn": "مازرونی",
"mer": "Kĩmĩrũ",
"mgo": "metaʼ",
"mn": "монгол",
"mfe": "kreol morisien",
"mua": "MUNDAŊ",
"mi": "Māori",
"naq": "Khoekhoegowab",
"ne": "नेपाली",
"nnh": "Shwóŋò ngiembɔɔn",
"jgo": "Ndaꞌa",
"yrl": "nheẽgatu",
"pcm": "Naijíriá Píjin",
"lrc": "لۊری شومالی",
"se": "davvisámegiella",
"nd": "isiNdebele",
"no": "norsk",
"nb": "norsk bokmål",
"nn": "norsk nynorsk",
"nus": "Thok Nath",
"nyn": "Runyankore",
"or": "ଓଡ଼ିଆ",
"om": "Oromoo",
"os": "ирон",
"ps": "پښتو",
"fa": "فارسی",
"pl": "polski",
"pt": "português",
"pa": "ਪੰਜਾਬੀ",
"qu": "Runasimi",
"raj": "राजस्थानी",
"ro": "română",
"rm": "rumantsch",
"rof": "Kihorombo",
"rn": "Ikirundi",
"ru": "русский",
"rwk": "Kiruwa",
"saq": "Kisampur",
"sg": "Sängö",
"sbp": "Ishisangu",
"sa": "संस्कृत भाषा",
"sat": "ᱥᱟᱱᱛᱟᱲᱤ",
"sc": "sardu",
"gd": "Gàidhlig",
"seh": "sena",
"sr": "српски",
"ksb": "Kishambaa",
"sn": "chiShona",
"ii": "ꆈꌠꉙ",
"sd": "سنڌي",
"si": "සිංහල",
"sk": "slovenčina",
"sl": "slovenščina",
"xog": "Olusoga",
"so": "Soomaali",
"es": "español",
"zgh": "ⵜⴰⵎⴰⵣⵉⵖⵜ",
"su": "Basa Sunda",
"sw": "Kiswahili",
"sv": "svenska",
"gsw": "Schwiizertüütsch",
"shi": "ⵜⴰⵛⵍⵃⵉⵜ",
"dav": "Kitaita",
"tg": "тоҷикӣ",
"ta": "தமிழ்",
"twq": "Tasawaq senni",
"tt": "татар",
"te": "తెలుగు",
"teo": "Kiteso",
"th": "ไทย",
"bo": "བོད་སྐད་",
"ti": "ትግርኛ",
"to": "lea fakatonga",
"tk": "türkmen dili",
"uk": "українська",
"hsb": "hornjoserbšćina",
"ur": "اردو",
"ug": "ئۇيغۇرچە",
"uz": "o‘zbek",
"vai": "ꕙꔤ",
"vi": "Tiếng Việt",
"vun": "Kyivunjo",
"wae": "Walser",
"cy": "Cymraeg",
"fy": "Frysk",
"wo": "Wolof",
"xh": "IsiXhosa",
"sah": "саха тыла",
"yav": "nuasue",
"yi": "ייִדיש",
"yo": "Èdè Yorùbá",
"dje": "Zarmaciine",
"zu": "isiZulu",
"is": "íslenska",
"ig": "Igbo",
"smn": "anarâškielâ",
"id": "Indonesia",
"ia": "interlingua",
"ga": "Gaeilge",
"it": "italiano"
    }

def translate(lang_dict, my_dictionary, lang, outputDir, locale=None):
    try:
        for name in my_dictionary:
            lang_dict[name] = ts.translate_text(my_dictionary[name], from_langauge="en", to_language=lang, translator=translator)

        if locale is None:
            locale = lang

        xmlOut = '<?xml version="1.0" encoding="utf-8"?><root><Lang Code="' + locales[lang] + '" DisplayName="' + languages[lang] + '" Locale="' + locale + '">'
        for name in lang_dict:
            xmlOut += '<Item Name="' + name + '" Value="' + lang_dict[name] + '" />'

        xmlOut += "</Lang></root>"

        dom = xml.dom.minidom.parseString(xmlOut)
        pretty_xml_as_string = dom.toprettyxml()
        f = open(os.path.join(outputDir, lang + ".xml"), "w")
        f.write(pretty_xml_as_string)
        f.close()
        print('DONE: ' + lang)
        return true
    except:
        if locale is None:
            locale_list = locales[lang].split(';')
            for lang_locale in locale_list:
                if translate(lang_dict, my_dictionary, lang, outputDir, lang_locale):
                    break
            return false



# Check if the correct number of arguments are provided
if len(sys.argv) != 3:
    print("Usage: python script.py input.xml outputDir [optional: translator]")
    sys.exit(1)


translator = 'bing'
if len(sys.argv) > 3:
    translator = sys.argv[3]

# _ = ts.preaccelerate_and_speedtest()

# Get the input XML file path from the command line argument
xml_file = sys.argv[1]
dir = sys.argv[2]

my_dictionary = {}

# Parse the XML file
try:
    tree = ET.parse(xml_file)
    root = tree.getroot()
    # Iterate over all nodes with the name "Item"
    for item in root.findall(".//Item"):
        # Get the Name and Value attributes
        name = item.get("Name")
        value = item.get("Value")
        my_dictionary[name] = value

except ET.ParseError:
    print("Error parsing the XML file.")
    sys.exit(1)

for lang in languages:
    if (lang != 'en'):
        lang_dict = {}
        try:
           translate(lang_dict, my_dictionary, lang, dir)

        except Exception as ex:
            print('Skipped language:' + lang)
            print('Exception caught:', ex)
            continue
